#
# NB! DO NOT USE THIS FOR PRODUCTION ENVIRONMENT
# THIS IS USED JUST FOR SETTING UP LOCAL ENVIRONMENT TO TEST THINGS OUT
#
version: '3.8'
services:
    php-apache-environment:
        container_name: web-server
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        env_file:
            - .env
            - secret.env
        ports:
            - 8443:80
        networks:
          - web-service
        develop:
          watch:
            - action: sync 
              path: ./
              target: /var/www/html
    db:
        container_name: db
        image: mysql:8.0
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        volumes:
          - ./App/Tests/Database:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: my-secret-pw
        ports:
            - "3306:3306"
        networks:
          - web-service
    adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080
        environment:
            PMA_HOST: db
        networks:
          - web-service
    mpd:
      image: tobi312/rpi-mpd:debian
      #image: tobi312/rpi-mpd:alpine
      container_name: mpd
      restart: unless-stopped
      ports:
        - 6600:6600  # MPD Client
        - 8000:8000  # Stream
      volumes:
        - ./public/music:/var/lib/mpd/music:rw
        #- ./playlists:/var/lib/mpd/playlists:rw
        #- ./data:/var/lib/mpd/data:rw
        #- ./mpd.conf:/etc/mpd.conf:rw
      #devices:
      #- "/dev/snd:/dev/snd"
      networks:
        - web-service
networks:
  web-service:
    driver: bridge
